version: "3.9"

services:
  ms-pedido-mysql:
    image: mysql:8.0.33
    container_name: ms-pedido-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33080:3306"
    environment:
      MYSQL_DATABASE: sistema_pedidos
      MYSQL_USER: sistema_pedidos
      MYSQL_PASSWORD: sistema_pedidos
      MYSQL_ROOT_PASSWORD: rootsql
      SERVICE_NAME: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ms-pedido-network
  
  ms-pedido-app:
    build: .
    container_name: sistema-pedido-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ms-pedido-mysql:3306/sistema_pedidos?useSSL=false&allowPublicKeyRetrieval=true"
    depends_on:
      ms-pedido-mysql:
        condition: service_healthy
    networks:
      - ms-pedido-network
  
  redis-server:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ms-pedido-network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  ms-pedido-network:
    driver: bridge

volumes:
  dados:
    driver: local
  dbdata:
    driver: local
