spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:33080/sistema_pedidos?useSSL=false&allowPublicKeyRetrieval=true
        username: sistema_pedidos
        password: ${DB_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
    sql:
        init:
            continue-on-error: true
            encoding: UTF-8
            mode: always
    cloud:
      openfeign:
        client:
            config:
                mercadopago:
                    default-request-headers:
                        Authorization:
                            - Bearer TEST-6416668675808261-012515-7dac31f086dd3bdf5d7137ace77d0ad1-1654958216
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: ${QUEUE_PASSWORD}

app:
    jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app-jwt-expiration-milliseconds: 604800000

springdoc:
    swagger-ui:
        operations-sorter: method
        tags-sorter: alpha

rest:
    service:
        ms-produto:
            url: http://localhost:8082
            context: v1
        ms-pagamento:
            url: http://localhost:8081
            context: v1

queue:
    filas:
        pedidos_criados: pedidos_criados
        pagamentos_nao_gerados: pagamentos_nao_gerados-dlq
        pagamentos_confirmados: pagamentos_confirmados
    exchange:
        fanoutPedido: pedidos.ex
        deadLetterPedido: pagamentos.dlx